
export const AUTH_USER = "AUTH/AUTH_USER"
export const LOGOUT_USER = "AUTH/LOGOUT_USER"
export const AUTH_ADMIN = "AUTH/AUTH_ADMIN"
export const LOGOUT_ADMIN = "AUTH/LOGOUT_ADMIN"

export const SET_USER_DATA = "USER/SET_USER_DATA"
export const REMOVE_USER_DATA = "USER/REMOVE_USER_DATA"
export const ADD_BALANCE = "USER/ADD_BALANCE"
export const MINUS_BALANCE = "USER/MINUS_BALANCE"
export const ADD_BALANCE_HISTORY = "USER/ADD_BALANCE_HISTORY"

export const SET_FOOD = "FOODS/SET_FOOD"
export const SET_ALL_FOODS = "FOODS/SET_ALL_FOODS"

export const ADD_CART = "CART/ADD_CART"
export const REMOVE_ITEM_IN_CARD = "CART/REMOVE_ITEM_IN_CARD"
export const INCREASE_QUANITY = "CART/INCREASE_QUANITY"
export const DECREASE_QUANITY = "CART/DECREASE_QUANITY"
export const SET_TOTAL_OF_CARD_ITEM = "CART/SET_TOTAL_OF_CARD_ITEM"
export const SET_IN_TOTAL = "CART/SET_IN_TOTAL"
export const CLEAR_CART = "CART/CLEAR_CART"



